In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, Input, Dropout, Attention
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import classification_report

In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv("/content/Chroma_Features_Main_Dataset.csv")
data

,0,1,2,3,4,5,6,7,8,9,10,11,gender,label
0,0.432488,0.491815,0.523997,0.518006,0.493282,0.470768,0.492656,0.536364,0.507345,0.544169,0.469461,0.420436,male,adult
1,0.550980,0.633927,0.632397,0.601437,0.520888,0.470092,0.455220,0.410089,0.454187,0.510549,0.494445,0.501295,male,adult
2,0.457489,0.474328,0.459457,0.449791,0.461657,0.453070,0.487244,0.497393,0.569792,0.589360,0.467036,0.448786,male,adult
3,0.463985,0.462935,0.458931,0.441836,0.446491,0.420002,0.442185,0.463970,0.509519,0.516826,0.460586,0.479687,male,adult
4,0.488712,0.520800,0.535209,0.495170,0.534017,0.560581,0.571302,0.516753,0.571805,0.562018,0.456434,0.494733,male,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.469901,0.541177,0.502391,0.400408,0.324453,0.237937,0.178894,0.209326,0.270576,0.262817,0.245056,0.297005,female,child
2996,0.393186,0.438162,0.412779,0.316119,0.334210,0.234454,0.261641,0.284742,0.272087,0.234631,0.213813,0.291997,female,child
2997,0.367361,0.466650,0.483502,0.395505,0.259017,0.227606,0.189038,0.152332,0.219846,0.401416,0.351640,0.289488,female,child
2998,0.428526,0.542809,0.402458,0.258381,0.181985,0.223265,0.122131,0.103100,0.179998,0.181975,0.170180,0.235630,female,child
2999,0.434809,0.548705,0.371845,0.341084,0.274912,0.208711,0.143083,0.133503,0.186074,0.258098,0.234705,0.198343,female,child

In [3]:
x = data.iloc[:, :-2]
y = data.iloc[:, -1]
data

,0,1,2,3,4,5,6,7,8,9,10,11,gender,label
0,0.432488,0.491815,0.523997,0.518006,0.493282,0.470768,0.492656,0.536364,0.507345,0.544169,0.469461,0.420436,male,adult
1,0.550980,0.633927,0.632397,0.601437,0.520888,0.470092,0.455220,0.410089,0.454187,0.510549,0.494445,0.501295,male,adult
2,0.457489,0.474328,0.459457,0.449791,0.461657,0.453070,0.487244,0.497393,0.569792,0.589360,0.467036,0.448786,male,adult
3,0.463985,0.462935,0.458931,0.441836,0.446491,0.420002,0.442185,0.463970,0.509519,0.516826,0.460586,0.479687,male,adult
4,0.488712,0.520800,0.535209,0.495170,0.534017,0.560581,0.571302,0.516753,0.571805,0.562018,0.456434,0.494733,male,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.469901,0.541177,0.502391,0.400408,0.324453,0.237937,0.178894,0.209326,0.270576,0.262817,0.245056,0.297005,female,child
2996,0.393186,0.438162,0.412779,0.316119,0.334210,0.234454,0.261641,0.284742,0.272087,0.234631,0.213813,0.291997,female,child
2997,0.367361,0.466650,0.483502,0.395505,0.259017,0.227606,0.189038,0.152332,0.219846,0.401416,0.351640,0.289488,female,child
2998,0.428526,0.542809,0.402458,0.258381,0.181985,0.223265,0.122131,0.103100,0.179998,0.181975,0.170180,0.235630,female,child
2999,0.434809,0.548705,0.371845,0.341084,0.274912,0.208711,0.143083,0.133503,0.186074,0.258098,0.234705,0.198343,female,child

In [4]:
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[0.59340385, 0.59454098, 0.57876471, ..., 0.77078666, 0.66463165,
        0.4021746 ],
       [0.79005022, 0.8208461 , 0.71882443, ..., 0.71340913, 0.7051875 ,
        0.49659565],
       [0.63489498, 0.56669249, 0.4953743 , ..., 0.84791309, 0.66069422,
        0.43527993],
       ...,
       [0.48532174, 0.55446686, 0.52644234, ..., 0.52715567, 0.47337227,
        0.24926222],
       [0.58682911, 0.67574664, 0.42172875, ..., 0.15264204, 0.17880902,
        0.18637004],
       [0.59725613, 0.68513525, 0.38217402, ..., 0.28255837, 0.28355275,
        0.14282897]])

In [5]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

array([0, 0, 0, ..., 1, 1, 1])

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

In [7]:

input_shape = (x_train.shape[1],)

In [14]:
class_weights = dict(enumerate(class_weight.compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)))

inputs = Input(shape=input_shape)
x = Dense(256, activation='relu')(inputs)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)

# Add Attention mechanism
attn_output = Attention()([x, x])

x = Dense(32, activation='tanh')(attn_output)
x = Dropout(0.5)(x)
outputs = Dense(1, activation='sigmoid')(x)

model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(patience=10, restore_best_weights=True)

model.fit(x_train, y_train, validation_data=(x_test, y_test), batch_size=32, epochs=20, callbacks=[early_stopping])

# Evaluate the model
_, train_accuracy = model.evaluate(x_train, y_train)
_, test_accuracy = model.evaluate(x_test, y_test)

print('Training Accuracy:', train_accuracy)
print('Testing Accuracy:', test_accuracy)

Epoch 1/20
75/75 [==============================] - 3s 13ms/step - loss: 0.6951 - accuracy: 0.4908 - val_loss: 0.6932 - val_accuracy: 0.4783
Epoch 2/20
75/75 [==============================] - 0s 6ms/step - loss: 0.6743 - accuracy: 0.5521 - val_loss: 0.5643 - val_accuracy: 0.8083
Epoch 3/20
75/75 [==============================] - 0s 6ms/step - loss: 0.5186 - accuracy: 0.7550 - val_loss: 0.3825 - val_accuracy: 0.8800
Epoch 4/20
75/75 [==============================] - 0s 4ms/step - loss: 0.4170 - accuracy: 0.8329 - val_loss: 0.2992 - val_accuracy: 0.8767
Epoch 5/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3806 - accuracy: 0.8429 - val_loss: 0.2841 - val_accuracy: 0.8850
Epoch 6/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3543 - accuracy: 0.8546 - val_loss: 0.2761 - val_accuracy: 0.9083
Epoch 7/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3548 - accuracy: 0.8637 - val_loss: 0.2760 - val_accuracy: 0.8783
Epoch 8/20
75/75 [==============================] - 0s 3ms/step - loss: 0.3133 - accuracy: 0.8813 - val_loss: 0.2516 - val_accuracy: 0.8933
Epoch 9/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3070 - accuracy: 0.8788 - val_loss: 0.2315 - val_accuracy: 0.9083
Epoch 10/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3031 - accuracy: 0.8946 - val_loss: 0.2664 - val_accuracy: 0.8917
Epoch 11/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3148 - accuracy: 0.8929 - val_loss: 0.2266 - val_accuracy: 0.9233
Epoch 12/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2950 - accuracy: 0.8921 - val_loss: 0.2631 - val_accuracy: 0.8917
Epoch 13/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2791 - accuracy: 0.8996 - val_loss: 0.2132 - val_accuracy: 0.9267
Epoch 14/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3022 - accuracy: 0.8875 - val_loss: 0.2773 - val_accuracy: 0.8800
Epoch 15/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2793 - accuracy: 0.8929 - val_loss: 0.3517 - val_accuracy: 0.8567
Epoch 16/20
75/75 [==============================] - 0s 4ms/step - loss: 0.3119 - accuracy: 0.8846 - val_loss: 0.2313 - val_accuracy: 0.9217
Epoch 17/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2835 - accuracy: 0.8971 - val_loss: 0.2069 - val_accuracy: 0.9217
Epoch 18/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2600 - accuracy: 0.9075 - val_loss: 0.2055 - val_accuracy: 0.9167
Epoch 19/20
75/75 [==============================] - 0s 3ms/step - loss: 0.2753 - accuracy: 0.9038 - val_loss: 0.1826 - val_accuracy: 0.9267
Epoch 20/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2658 - accuracy: 0.9046 - val_loss: 0.2013 - val_accuracy: 0.9183
75/75 [==============================] - 0s 2ms/step - loss: 0.2048 - accuracy: 0.9250
19/19 [==============================] - 0s 2ms/step - loss: 0.2013 - accuracy: 0.9183
Training Accuracy: 0.925000011920929
Testing Accuracy: 0.9183333516120911

In [15]:
#4
input_sample=[0.686712, 0.640698, 0.593252, 0.550928, 0.636928, 0.777290, 0.868471, 0.728977, 0.821275, 0.801250, 0.643484, 0.488934]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 12, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 226ms/step
[[0]]

In [17]:
#1499
input_sample=[0.486863, 0.364883, 0.282707, 0.291565, 0.310914, 0.390962, 0.487632, 0.458521, 0.376474, 0.499133, 0.656269, 0.393245]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 12, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 23ms/step
[[0]]

In [18]:
#1500
input_sample=[1.000000, 0.592887, 0.273069, 0.097997, 0.057796, 0.114112, 0.233302, 0.366464, 0.311509, 0.276021, 0.594875, 0.586872]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 12, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 21ms/step
[[1]]

In [19]:
#2599
input_sample=[0.377813, 0.359893, 0.395458, 0.499061, 0.462250, 0.314258, 0.192029, 0.224185, 0.379166, 0.431067, 0.295571, 0.195259]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 12, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 24ms/step
[[1]]

In [20]:
model.save('Chroma_AS_Age_Estimation.h5')